/* HSK 4 上 interactive course — lessons 1–10 */
'use strict';
const SITE_UNLOCK_KEY='hsk_site_unlocked_v1';
const STORAGE_KEY='hsk4_upper_ranteacher_progress_v1';
const PASSWORD_HASH='7cdee08809e6b166a8e8a9ecd162ffdd4395a7f1c5c76a10f96bacd5a7447da1';
const PASSWORD_SIG='7136.8001.5e08.6700.7f8e';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const unique=a=>[...new Set(a)];
const sections=[['vocab','Từ vựng'],['text','Bài khoá'],['grammar','Ngữ pháp'],['hanzi','Hán tự'],['practice','Luyện tập']];
const secOrder=sections.map(x=>x[0]);
const secNames={vocab:'Từ vựng · 生词',text:'Bài khoá · 课文',grammar:'Ngữ pháp · 语言点',hanzi:'Hán tự · 汉字笔顺',practice:'Luyện tập · 练习'};
let id=1,L=null,currentSec='vocab',sceneIndex=0,hanziWriter=null,hanziSelected='';
const pyCache=new Map();

function passSig(text){return [...text].map(c=>c.codePointAt(0).toString(16)).join('.')}
async function sha256(text){if(!globalThis.crypto?.subtle)return null;const d=new TextEncoder().encode(text),h=await crypto.subtle.digest('SHA-256',d);return [...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function checkPassword(){const input=$('#pwInput'),err=$('#pwError'),btn=$('#pwBtn');if(!input)return;btn.disabled=true;const raw=input.value.trim(),digest=await sha256(raw),ok=digest?digest===PASSWORD_HASH:passSig(raw)===PASSWORD_SIG;btn.disabled=false;if(ok){localStorage.setItem(SITE_UNLOCK_KEY,'1');sessionStorage.setItem('hsk_portal_unlocked','1');sessionStorage.setItem('hsk4_upper_ranteacher_unlocked','1');$('#pwOverlay').style.display='none';document.body.style.overflow=''}else{err?.classList.add('show');input.select()}}
function initGate(){const o=$('#pwOverlay');if(!o)return;if(localStorage.getItem(SITE_UNLOCK_KEY)==='1'||sessionStorage.getItem('hsk_portal_unlocked')==='1'||sessionStorage.getItem('hsk4_upper_ranteacher_unlocked')==='1'){o.style.display='none';document.body.style.overflow=''}else{document.body.style.overflow='hidden';$('#pwInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')checkPassword()})}}
function toast(msg){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1700)}
function getProgress(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}}
function saveProgress(p){localStorage.setItem(STORAGE_KEY,JSON.stringify(p))}
function resetCourse(){if(confirm('Xóa toàn bộ tiến độ HSK 4 上 trên trình duyệt này?')){localStorage.removeItem(STORAGE_KEY);location.reload()}}
function markVisited(n){const p=getProgress();p[n]??={};p[n].visited=true;saveProgress(p)}
function toggleComplete(){const p=getProgress();p[id]??={};p[id].complete=!p[id].complete;saveProgress(p);renderComplete();toast(p[id].complete?'Đã đánh dấu hoàn thành.':'Đã bỏ đánh dấu hoàn thành.')}
function renderComplete(){const b=$('#completeBtn');if(!b)return;const done=!!getProgress()[id]?.complete;b.textContent=done?'✓ Đã hoàn thành':'✓ Đánh dấu hoàn thành';b.classList.toggle('done',done)}
function speak(text){if(!('speechSynthesis' in window)){toast('Trình duyệt chưa hỗ trợ phát âm.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang='zh-CN';u.rate=.82;const vs=speechSynthesis.getVoices?.()||[];u.voice=vs.find(v=>/zh|Chinese|Mandarin/i.test((v.lang||'')+' '+(v.name||'')))||null;speechSynthesis.speak(u)}
function pyOf(text){if(pyCache.has(text))return pyCache.get(text);let out='';try{if(window.pinyinPro?.pinyin)out=window.pinyinPro.pinyin(text,{toneType:'symbol',type:'array'}).join(' ')}catch(e){}pyCache.set(text,out);return out}
function seededShuffle(items,seed){const a=[...items];let x=(seed||1)>>>0;const rnd=()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296};for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}

function validateData(){const A=window.HSK4_UPPER_LESSONS;if(!Array.isArray(A)||A.length!==10)throw new Error('HSK 4 上 phải có đúng 10 bài (1–10).');const expectedTitles=['简单的爱情','真正的朋友','经理对我印象不错。','不要太着急赚钱。','只买对的，不买贵的。','一分钱一分货。','最好的医生是自己。','生活中不缺少美。','阳光总在风雨后。','幸福的标准'];const expectedCounts=[32,30,31,31,31,31,33,29,31,30];A.forEach((x,i)=>{if(x.id!==i+1)throw new Error(`Sai thứ tự bài ${x.id}; cần ${i+1}.`);if(x.title!==expectedTitles[i])throw new Error(`Sai tiêu đề bài ${x.id}.`);if(x.vocab?.length!==expectedCounts[i])throw new Error(`Bài ${x.id}: số từ phải là ${expectedCounts[i]}.`);if(x.grammar?.length!==5)throw new Error(`Bài ${x.id}: phải có 5 điểm ngôn ngữ.`);if(x.scenes?.length!==5)throw new Error(`Bài ${x.id}: phải có 5 bài khoá.`);if(!x.compare?.title||!x.expansion?.char||!x.culture?.title)throw new Error(`Bài ${x.id}: thiếu 比一比 / 同字词 / 文化.`);const set=new Set;for(const [j,w] of x.vocab.entries()){if(!w.zh||!w.vn)throw new Error(`Bài ${x.id}, từ ${j+1}: thiếu dữ liệu.`);if(set.has(w.zh))throw new Error(`Bài ${x.id}: trùng từ ${w.zh}.`);set.add(w.zh)}x.grammar.forEach((q,j)=>{if(!q.title||!q.vn_title||!q.structure||!q.desc||q.examples?.length<2)throw new Error(`Bài ${x.id}, ngữ pháp ${j+1}: thiếu dữ liệu.`)});x.scenes.forEach((s,j)=>{if(!s.title||!s.vn_title||!s.summary||String(s.points||'').split('|').length<2)throw new Error(`Bài ${x.id}, bài khoá ${j+1}: thiếu dữ liệu.`)});if(!x.comprehension?.length||!x.tasks?.retell?.length||!x.tasks?.application?.length)throw new Error(`Bài ${x.id}: thiếu bài tập mở rộng.`)});return A}
function showFatal(err){console.error('[HSK4 Upper]',err);const target=$('#lessonGrid')||$('.lesson-container')||$('main');if(target){const d=document.createElement('div');d.className='fatal-box';d.innerHTML=`<b>Không tải được HSK 4 上.</b><br>${esc(err?.message||String(err))}`;target.prepend(d)}}

function renderHome(){const A=window.HSK4_UPPER_LESSONS,p=getProgress(),grid=$('#lessonGrid');let done=0,words=0;grid.innerHTML='';A.forEach(x=>{words+=x.vocab.length;const ok=!!p[x.id]?.complete;if(ok)done++;const pct=ok?100:(p[x.id]?.visited?32:0);const c=document.createElement('article');c.className='lesson-card';c.innerHTML=`<a class="lesson-main-link" href="lesson.html?id=${x.id}&sec=vocab"><div class="lesson-num">第 ${x.id} 课 ${ok?'· ✓ Đã học':''}</div><div class="lesson-title zh">${esc(x.title)}</div><div class="lesson-vn">${esc(x.vn_title)}</div><div class="lesson-meta-line"><span>${x.vocab.length} 生词</span><span>5 语言点</span><span>5 课文</span><span>文化</span></div></a><div class="lesson-open-row"><a class="lesson-open-all" href="lesson.html?id=${x.id}&sec=vocab">Mở bài</a>${sections.map(([sec,label])=>`<a href="lesson.html?id=${x.id}&sec=${sec}">${label}</a>`).join('')}</div><div class="mini-progress"><i style="width:${pct}%"></i></div>`;grid.appendChild(c)});$('#wordStat').textContent=words;$('#doneStat').textContent=done+'/10';$('#progressSummary').textContent='Tiến độ '+Math.round(done/10*100)+'%'}

function initLesson(){const u=new URL(location.href);id=Math.max(1,Math.min(10,parseInt(u.searchParams.get('id')||'1',10)));L=window.HSK4_UPPER_LESSONS.find(x=>x.id===id)||window.HSK4_UPPER_LESSONS[0];currentSec=secOrder.includes(u.searchParams.get('sec'))?u.searchParams.get('sec'):'vocab';markVisited(id);renderLessonShell();renderVocab();renderText();renderGrammar();renderHanzi();renderPractice();showSection(currentSec,false);renderComplete()}
function renderLessonShell(){document.title=`HSK 4 上 · Bài ${id} · ${L.title}`;$('#lessonTitle').textContent=L.title;$('#lessonVn').textContent=L.vn_title;$('#lessonTag').textContent=`第 ${id} 课 · 标准教程 4（上）· 教材第 ${L.page} 页`;$('#vocabCount').textContent=L.vocab.length;$('#grammarCount').textContent=L.grammar.length;$('#vocabChip').textContent=L.vocab.length+' từ/cụm';$('#grammarChip').textContent='5 điểm + 比一比';const sel=$('#lessonSelect');sel.innerHTML=window.HSK4_UPPER_LESSONS.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>Bài ${x.id} · ${esc(x.title)}</option>`).join('');sel.onchange=()=>location.href=`lesson.html?id=${sel.value}&sec=${currentSec}`;$$('.section-tab[data-sec]').forEach(b=>b.onclick=()=>showSection(b.dataset.sec));renderLessonSwitch();setupModuleNav()}
function showSection(sec,push=true){if(!secOrder.includes(sec))sec='vocab';currentSec=sec;$$('.content-section').forEach(x=>x.classList.toggle('active',x.id===sec));$$('.section-tab[data-sec]').forEach(x=>x.classList.toggle('active',x.dataset.sec===sec));$('#moduleStepTitle').textContent=secNames[sec];const i=secOrder.indexOf(sec);$('#prevModuleBtn').disabled=i===0;$('#nextModuleBtn').textContent=i===4?'Về từ vựng ↺':'Mục tiếp theo →';if(push){const u=new URL(location.href);u.searchParams.set('sec',sec);history.replaceState(null,'',u);window.scrollTo({top:0,behavior:'smooth'})}}
function setupModuleNav(){$('#prevModuleBtn').onclick=()=>{const i=secOrder.indexOf(currentSec);if(i>0)showSection(secOrder[i-1])};$('#nextModuleBtn').onclick=()=>{const i=secOrder.indexOf(currentSec);showSection(secOrder[(i+1)%5])}}
function renderLessonSwitch(){const prev=id>1?`<a class="ghost-btn" href="lesson.html?id=${id-1}&sec=${currentSec}">← Bài ${id-1}</a>`:'<span></span>';const next=id<10?`<a class="primary-btn" href="lesson.html?id=${id+1}&sec=${currentSec}">Bài ${id+1} →</a>`:'<a class="primary-btn" href="index.html">Về HSK 4 上</a>';$('#lessonSwitch').innerHTML=prev+next}
