function renderVocab(){
  const q=$('#vSearch'),grid=$('#vocabGrid');
  function draw(term=''){const t=term.trim().toLowerCase(),items=L.vocab.filter(w=>!t||[w.zh,pyOf(w.zh),w.vn].some(x=>String(x).toLowerCase().includes(t)));grid.innerHTML=items.map((w,i)=>`<article class="vcard" data-zh="${esc(w.zh)}"><div class="vinner"><div class="vface vfront"><div class="vno">${L.vocab.indexOf(w)+1}</div><div class="vzh">${esc(w.zh)}</div><div class="vpy">${esc(pyOf(w.zh))}</div><div class="vactions"><button class="tiny listen">🔊</button><button class="tiny flip">↻</button></div></div><div class="vface vback"><div class="vvn">${esc(w.vn)}</div><div class="vpy">${esc(pyOf(w.zh))}</div><small>Chạm để lật lại</small></div></div></article>`).join('');
    $$('.vcard',grid).forEach(card=>{const w=L.vocab.find(x=>x.zh===card.dataset.zh);card.onclick=e=>{if(e.target.closest('.listen')){e.stopPropagation();speak(w.zh);return}card.classList.toggle('flipped');showWordDetail(w)};$('.flip',card)?.addEventListener('click',e=>{e.stopPropagation();card.classList.toggle('flipped');showWordDetail(w)})});if(items[0])showWordDetail(items[0]);}
  q.oninput=()=>draw(q.value);draw();
}
function showWordDetail(w){$('#wordPanel').innerHTML=`<div class="word-detail"><div><div class="word-main">${esc(w.zh)}</div><div class="word-py">${esc(pyOf(w.zh))}</div><div class="word-context">${esc(w.vn)}</div></div><button class="ghost-btn" onclick='speak(${JSON.stringify(w.zh)})'>🔊 Nghe phát âm</button></div>`}
function flipAll(){$$('.vcard').forEach(c=>c.classList.toggle('flipped'))}
function speakAllVocab(){speak(L.vocab.map(x=>x.zh).join('，'))}
function pointsOf(s){return String(s.points||'').split('|').filter(Boolean)}
function renderText(){
  sceneIndex=0;const tabs=$('#sceneTabs');tabs.innerHTML=L.scenes.map((s,i)=>`<button class="scene-tab ${i===0?'active':''}" data-i="${i}">${i+1}. ${esc(s.vn_title)}</button>`).join('');
  $$('.scene-tab',tabs).forEach(b=>b.onclick=()=>{sceneIndex=+b.dataset.i;$$('.scene-tab',tabs).forEach(x=>x.classList.toggle('active',x===b));drawScene()});drawScene();
}
function drawScene(){const s=L.scenes[sceneIndex],pts=pointsOf(s);$('#scenePane').innerHTML=`<article class="text-card"><div class="text-card-head"><div><span class="text-no">${s.title}</span><h3>${esc(s.vn_title)}</h3></div><button class="ghost-btn" onclick='speak(${JSON.stringify(pts.join('，'))})'>🔊 Nghe câu trọng điểm</button></div><div class="text-summary">${esc(s.summary)}</div><div class="key-lines">${pts.map(x=>`<div class="key-line"><div><div class="line-py">${esc(pyOf(x))}</div><div class="line-zh">${esc(x)}</div></div><button onclick='speak(${JSON.stringify(x)})'>🔊</button></div>`).join('')}</div><div class="source-boundary">教材位置：第 ${L.id} 课 · ${s.title}。</div></article>`}
function renderGrammar(){
  const gl=$('#grammarList');gl.innerHTML=L.grammar.map((g,i)=>`<article class="grammar-card"><div class="grammar-index">${i+1}</div><h3>${esc(g.title)}</h3><div class="grammar-vn-title">${esc(g.vn_title)}</div><div class="grammar-structure">${esc(g.structure)}</div><div class="grammar-desc">${esc(g.desc)}</div><div class="grammar-examples">${g.examples.map(e=>`<div class="grammar-example"><div><div class="line-py">${esc(pyOf(e))}</div><span>${esc(e)}</span></div><button onclick='speak(${JSON.stringify(e)})'>🔊</button></div>`).join('')}</div></article>`).join('');
  $('#comparePanel').innerHTML=`<div class="feature-head"><span>比一比 · SO SÁNH</span><b>${esc(L.compare.title)}</b></div><p>${esc(L.compare.vn)}</p>${L.compare.examples.map(e=>`<div class="mini-example"><span>${esc(e)}</span><button onclick='speak(${JSON.stringify(e)})'>🔊</button></div>`).join('')}`;
  $('#expansionPanel').innerHTML=`<div class="feature-head"><span>扩展 · 同字词</span><b>${esc(L.expansion.char)}</b></div><div class="expansion-words">${L.expansion.words.map(w=>`<span>${esc(w)}</span>`).join('')}</div><p>${esc(L.expansion.vn)}</p>`;
  $('#culturePanel').innerHTML=`<div class="feature-head"><span>文化 · VĂN HÓA</span><b>${esc(L.culture.title)}</b></div><p>${esc(L.culture.vn)}</p>`;
}
function uniqueHanzi(){const out=[];L.vocab.forEach(w=>[...w.zh].forEach(ch=>{if(/[\u3400-\u9fff\uf900-\ufaff]/.test(ch)&&!out.includes(ch))out.push(ch)}));return out}
function renderHanzi(){const chars=uniqueHanzi();$('#hanziChip').textContent=chars.length+' chữ';$('#hanziWordMap').innerHTML=`<div class="hanzi-char-list">${chars.map((c,i)=>`<button class="hanzi-char-btn ${i===0?'active':''}" data-char="${c}">${c}</button>`).join('')}</div>`;$$('.hanzi-char-btn').forEach(b=>b.onclick=()=>{$$('.hanzi-char-btn').forEach(x=>x.classList.toggle('active',x===b));drawHanzi(b.dataset.char)});if(chars[0])drawHanzi(chars[0])}
function drawHanzi(ch){hanziSelected=ch;hanziWriter=null;const words=L.vocab.filter(w=>w.zh.includes(ch));$('#hanziMaster').innerHTML=`<div class="hanzi-canvas-wrap"><div id="hanziCanvas"><div class="hanzi-static">${ch}</div></div></div><div class="hanzi-info"><h3>${ch}</h3><p>Chọn chữ trong từ mới để xem từ liên quan, phát âm và luyện thứ tự nét.</p><div class="hanzi-words">${words.map(w=>`<span><b>${esc(w.zh)}</b> · ${esc(pyOf(w.zh))} · ${esc(w.vn)}</span>`).join('')}</div><div class="hanzi-controls"><button class="primary-btn" onclick="animateHanzi()">▶ Xem bút thuận</button><button class="ghost-btn" onclick="quizHanzi()">✍ Luyện viết</button><button class="ghost-btn" onclick="speak('${ch}')">🔊 Nghe</button></div><div id="hanziStatus"></div></div>`;ensureWriter(false)}
function ensureWriter(status=true){if(hanziWriter)return true;if(!window.HanziWriter){if(status)$('#hanziStatus').textContent='Tạm thời chưa tải được bút thuận; hãy thử lại sau.';return false}const box=$('#hanziCanvas');box.innerHTML='';try{hanziWriter=HanziWriter.create('hanziCanvas',hanziSelected,{width:230,height:230,padding:12,showOutline:true,strokeAnimationSpeed:1,delayBetweenStrokes:180,drawingWidth:4,showCharacter:false});return true}catch(e){console.error(e);if(status)$('#hanziStatus').textContent='Tạm thời chưa tải được dữ liệu nét cho chữ này.';return false}}
function animateHanzi(){if(!ensureWriter())return;$('#hanziStatus').textContent='Đang phát thứ tự nét…';hanziWriter.animateCharacter({onComplete:()=>$('#hanziStatus').textContent='✓ Đã phát xong.'})}
function quizHanzi(){if(!ensureWriter())return;$('#hanziStatus').textContent='Hãy viết theo đúng thứ tự nét.';hanziWriter.quiz({onComplete:d=>$('#hanziStatus').textContent=`✓ Hoàn thành · sai ${d.totalMistakes||0} lần.`})}
