let selectedMC={},selectedGrammar={},selectedRead={};
function allVocab(){return window.HSK4_LOWER_LESSONS.flatMap(x=>x.vocab)}
function allGrammar(){return window.HSK4_LOWER_LESSONS.flatMap(x=>x.grammar)}
function renderPractice(){
  $('#basicPractice').innerHTML=`<div class="quiz-tabs"><button class="quiz-tab active" data-q="mc">Từ vựng</button><button class="quiz-tab" data-q="fill">Điền từ</button><button class="quiz-tab" data-q="grammar">Ngữ pháp</button><button class="quiz-tab" data-q="read">Đọc hiểu</button></div><div class="quiz-pane active" id="q-mc"></div><div class="quiz-pane" id="q-fill"></div><div class="quiz-pane" id="q-grammar"></div><div class="quiz-pane" id="q-read"></div><div class="scorebar" id="scoreText">Làm bài và nộp để xem đáp án + giải thích.</div>`;
  $$('.quiz-tab',$('#basicPractice')).forEach(b=>b.onclick=()=>{$$('.quiz-tab',$('#basicPractice')).forEach(x=>x.classList.toggle('active',x===b));$$('.quiz-pane',$('#basicPractice')).forEach(x=>x.classList.toggle('active',x.id==='q-'+b.dataset.q))});
  renderMC();renderFill();renderGrammarQuiz();renderReadQuiz();renderAdvanced();
}
function optionCards(qs,key,target,checker){window[key]=qs;const selected=key==='_mcQs'?selectedMC:key==='_gQs'?selectedGrammar:selectedRead;selectedMC=key==='_mcQs'?{}:selectedMC;selectedGrammar=key==='_gQs'?{}:selectedGrammar;selectedRead=key==='_rQs'?{}:selectedRead;const state=key==='_mcQs'?selectedMC:key==='_gQs'?selectedGrammar:selectedRead;
  $(target).innerHTML=qs.map((q,i)=>`<div class="qcard" data-i="${i}"><div class="qmeta"><span>Câu ${i+1}/${qs.length}</span></div><div class="qtitle">${esc(q.q)}</div><div class="opts">${q.opts.map(o=>`<button class="opt" data-val="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="feedback"></div></div>`).join('')+`<div class="quiz-actions"><button class="primary-btn" onclick="${checker}()">✓ Nộp bài</button></div>`;
  $$('.qcard',$(target)).forEach((c,i)=>$$('.opt',c).forEach(b=>b.onclick=()=>{if(c.dataset.checked)return;$$('.opt',c).forEach(x=>x.classList.remove('sel'));b.classList.add('sel');state[i]=b.dataset.val}));
}
function renderMC(){const pool=allVocab(),qs=L.vocab.slice(0,8).map(w=>{const ds=shuffle(unique(pool.filter(x=>x.zh!==w.zh).map(x=>x.vn))).slice(0,3);return{q:`“${w.zh}” (${pyOf(w.zh)}) nghĩa là gì?`,opts:shuffle([w.vn,...ds]),ans:w.vn,why:`${w.zh} = ${w.vn}.`}});optionCards(qs,'_mcQs','#q-mc','checkMC')}
function checkOptions(target,qs,state,label){let ok=0;$$('.qcard',$(target)).forEach((c,i)=>{const q=qs[i],chosen=state[i],good=chosen===q.ans;c.dataset.checked='1';$$('.opt',c).forEach(b=>{b.disabled=true;if(b.dataset.val===q.ans)b.classList.add('correct');if(b.classList.contains('sel')&&!good)b.classList.add('wrong')});if(good)ok++;const f=$('.feedback',c);f.innerHTML=`<div>${good?'✅ Đúng':chosen?'❌ Chưa đúng':'⚠️ Chưa chọn'} · Đáp án: <b>${esc(q.ans)}</b></div><div class="answer-explain"><b>解析 · Giải thích</b><div>${esc(q.why)}</div></div>`;f.className='feedback '+(good?'good':'bad')});$('#scoreText').textContent=`${label}: ${ok}/${qs.length} · ${Math.round(ok/qs.length*100)}%`}
function checkMC(){checkOptions('#q-mc',window._mcQs,selectedMC,'Từ vựng')}
function renderFill(){const items=L.vocab.slice(8,13);$('#q-fill').innerHTML=items.map((w,i)=>`<div class="fill-card"><b>${i+1}.</b> Viết từ tiếng Trung cho “${esc(w.vn)}”: <input class="fill-input" data-i="${i}" autocomplete="off"><div class="feedback" id="fillfb-${i}"></div></div>`).join('')+`<div class="quiz-actions"><button class="primary-btn" onclick="checkFill()">✓ Kiểm tra</button></div>`;window._fillItems=items}
function checkFill(){let ok=0;$$('.fill-input',$('#q-fill')).forEach(inp=>{const w=window._fillItems[+inp.dataset.i],good=norm(inp.value)===norm(w.zh);if(good)ok++;inp.classList.toggle('good',good);inp.classList.toggle('bad',!good);const f=$('#fillfb-'+inp.dataset.i);f.innerHTML=`${good?'✅':'❌'} Đáp án: <b>${esc(w.zh)}</b> ${esc(pyOf(w.zh))}`;f.className='feedback '+(good?'good':'bad')});$('#scoreText').textContent=`Điền từ: ${ok}/${window._fillItems.length} · ${Math.round(ok/window._fillItems.length*100)}%`}
function renderGrammarQuiz(){const pool=allGrammar();const qs=L.grammar.map(g=>{const ds=shuffle(unique(pool.filter(x=>x.title!==g.title).map(x=>x.vn_title))).slice(0,3);return{q:`Cấu trúc “${g.title}” trong bài này chủ yếu dùng thế nào?`,opts:shuffle([g.vn_title,...ds]),ans:g.vn_title,why:`${g.desc} Mẫu: ${g.structure}`}});optionCards(qs,'_gQs','#q-grammar','checkGrammarQuiz')}
function checkGrammarQuiz(){checkOptions('#q-grammar',window._gQs,selectedGrammar,'Ngữ pháp')}
function renderReadQuiz(){const qs=L.scenes.map((s,i)=>{const correct=pointsOf(s)[0],ds=shuffle(L.scenes.filter((_,j)=>j!==i).map(x=>pointsOf(x)[0])).slice(0,3);return{q:`Câu nào phù hợp với ý chính của ${s.title} – ${s.vn_title}?`,opts:shuffle([correct,...ds]),ans:correct,why:s.summary}});optionCards(qs,'_rQs','#q-read','checkReadQuiz')}
function checkReadQuiz(){checkOptions('#q-read',window._rQs,selectedRead,'Đọc hiểu')}
function renderAdvanced(){
  const qs=L.grammar.map((g,i)=>{const ex=g.examples[i%g.examples.length],others=shuffle(L.grammar.filter(x=>x!==g).map(x=>x.title)).slice(0,3);return{q:`Câu “${ex}” minh họa điểm ngôn ngữ nào?`,opts:shuffle([g.title,...others]),ans:g.title,why:`${g.vn_title}: ${g.desc}`}});
  $('#advancedPractice').innerHTML=`<div class="advanced-intro"><div><span class="advanced-badge">进阶测试 · NÂNG CAO</span><h3>Nhận diện cấu trúc trong ngữ cảnh</h3><p>5 câu bám đúng 5 điểm ngôn ngữ của Bài ${id}.</p></div><div class="advanced-count">5 câu</div></div><div class="advanced-score" id="advancedScore">Làm đủ câu rồi bấm “Nộp bài nâng cao”.</div>`+qs.map((q,i)=>`<div class="qcard advanced-card" data-i="${i}"><div class="qmeta"><span>Nâng cao ${i+1}/5</span><span class="difficulty-chip">HSK 4</span></div><div class="qtitle">${esc(q.q)}</div><div class="opts">${q.opts.map(o=>`<button class="opt" data-val="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="feedback"></div></div>`).join('')+`<div class="quiz-actions"><button class="primary-btn" onclick="checkAdvanced()">✓ Nộp bài nâng cao</button></div>`;window._advQs=qs;window._advSel={};$$('.advanced-card',$('#advancedPractice')).forEach((c,i)=>$$('.opt',c).forEach(b=>b.onclick=()=>{if(c.dataset.checked)return;$$('.opt',c).forEach(x=>x.classList.remove('sel'));b.classList.add('sel');window._advSel[i]=b.dataset.val}))}
function checkAdvanced(){let ok=0;$$('.advanced-card',$('#advancedPractice')).forEach((c,i)=>{const q=window._advQs[i],chosen=window._advSel[i],good=chosen===q.ans;c.dataset.checked='1';$$('.opt',c).forEach(b=>{b.disabled=true;if(b.dataset.val===q.ans)b.classList.add('correct');if(b.classList.contains('sel')&&!good)b.classList.add('wrong')});if(good)ok++;const f=$('.feedback',c);f.innerHTML=`<div>${good?'✅ Đúng':'❌ Chưa đúng'} · <b>${esc(q.ans)}</b></div><div class="answer-explain"><b>解析</b><div>${esc(q.why)}</div></div>`;f.className='feedback '+(good?'good':'bad')});$('#advancedScore').textContent=`Nâng cao: ${ok}/5 · ${ok*20}%`}
function boot(){
  try{validateData();initGate();if($('#lessonGrid'))renderHome();if($('#lessonTitle'))initLesson();document.documentElement.dataset.hsk4Runtime='ok';window.__HSK4_LOWER_RUNTIME_OK=true;window.__HSK4_LOWER_DIAGNOSTICS={ok:true,lessons:10,words:window.HSK4_LOWER_LESSONS.reduce((n,L)=>n+L.vocab.length,0),page:$('#lessonGrid')?'home':'lesson'};console.info('[HSK4 Lower] OK',window.__HSK4_LOWER_DIAGNOSTICS)}catch(e){showFatal(e)}
}
if(!window.HSK4_BOOT_DISABLE_AUTO){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()}
